addSbtPlugin("io.spray"           % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.lucidchart"     % "sbt-scalafmt"        % "1.15")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver"  % "0.13.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"         % "0.3.3")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "1.5.1")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"          % "2.0.0")
addSbtPlugin("com.lightbend.sbt"  % "sbt-javaagent"       % "0.1.4")
resolvers += Resolver.bintrayRepo("kamon-io", "sbt-plugins")
addSbtPlugin("io.kamon" % "sbt-aspectj-runner" % "1.0.4")
